name: tic_tac_toe
description: Implementation is Tic Tac Toe using Dart and Deact.
version: 1.0.0
homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  deact: ^1.2.0

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^4.0.11
  lints: ^5.0.0
